import "%modules%/main-top/main-top";
import "%modules%/scheme/scheme";
import "%modules%/team/team";
import "%modules%/reviews/reviews-messengers";
import "%modules%/reviews/reviews-letters";
import "%modules%/certificates/certificates";
import "%modules%/cases/cases";
import "%modules%/rewards/rewards";
import "%modules%/numbers/numbers";
